### ISSUE TITLE
Cannot get HlsMediaPlaylist

### ISSUE THREAD

**Issue by Kazem-ma79** [tmk907/PlaylistsNET#20]
HlsMediaContent videoContent = new();
var videoFiles = videoContent.GetFromString(video);

Getting `Value was either too large or too small for an Int32` on GetFromString().

**Comment by tmk907** [comment]
Can you share the playlist that causes the error?

**Comment by Kazem-ma79** [comment]
> Can you share the playlist that causes the error?

https://cdn.telewebion.com/tv1/episode/0x2871a5c/240p/index.m3u8

**Comment by tmk907** [comment]
Fixed in 1.2.0. I changed MediaSequence and DiscontinuitySequence type to long.
