### ISSUE TITLE
GetTracksPaths Strips Plus Sign Character

### ISSUE THREAD

**Issue by skincer357** [tmk907/PlaylistsNET#23]
GetTracksPaths is removing a plus sign (+) from a folder name.

I have a playlist that contains:
#EXTINF:0,01 - Gonna Make You Sweat (Everybody Dance Now).mp3
.\C+C Music Factory\Gonna Make You Sweat\01 - Gonna Make You Sweat (Everybody Dance Now).mp3

When I execute the following code:
            PlaylistsNET.Content.M3uContent content = new PlaylistsNET.Content.M3uContent();
            using (StreamReader sr = new StreamReader(@"M:\Test_Playlist.m3u"))
            {
                PlaylistsNET.Models.M3uPlaylist MyPlaylist = content.GetFromStream(sr.BaseStream);
                foreach (var track in MyPlaylist.GetTracksPaths())
                {
                    Console.WriteLine(track);
                }
            }

I see:
.\C C Music Factory\Gonna Make You Sweat\01 - Gonna Make You Sweat (Everybody Dance Now).mp3

Thanks.
Steve

**Comment by tmk907** [comment]
Plus sign is removed because path is decoded using WebUtility.UrlDecode(). This was done to fix https://github.com/tmk907/PlaylistsNET/issues/12

**Comment by skincer357** [comment]
Thanks for making the change.  When can I expect to see this published to nuget?
Steve

**Comment by skincer357** [comment]
Works great.

Thanks.

Steve
